# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ABImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RotateImage = channel.unary_unary(
                '/ABImageService/RotateImage',
                request_serializer=image__pb2.ABImageRotateRequest.SerializeToString,
                response_deserializer=image__pb2.ABImage.FromString,
                )
        self.RecognizeFace = channel.unary_unary(
                '/ABImageService/RecognizeFace',
                request_serializer=image__pb2.ABCustomImageEndpointRequest.SerializeToString,
                response_deserializer=image__pb2.ABCustomImageEndpointResponse.FromString,
                )


class ABImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RotateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ABImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RotateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateImage,
                    request_deserializer=image__pb2.ABImageRotateRequest.FromString,
                    response_serializer=image__pb2.ABImage.SerializeToString,
            ),
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=image__pb2.ABCustomImageEndpointRequest.FromString,
                    response_serializer=image__pb2.ABCustomImageEndpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ABImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ABImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RotateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ABImageService/RotateImage',
            image__pb2.ABImageRotateRequest.SerializeToString,
            image__pb2.ABImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ABImageService/RecognizeFace',
            image__pb2.ABCustomImageEndpointRequest.SerializeToString,
            image__pb2.ABCustomImageEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
